# netlify.toml — aquilario.com (marketing)

# Security headers (keep if you want)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

# Redirect short path to the app subdomain
[[redirects]]
  from = "/linkconvert"
  to = "https://linkconvert.aquilario.com"
  status = 308
  force = true

[[redirects]]
  from = "/linkconvert/*"
  to = "https://linkconvert.aquilario.com/:splat"
  status = 308
  force = true

  [[redirects]]
  from = "/linkconvertbeta/*"
  to = "https://linkconvert.aquilario.com/:splat"
  status = 301



