[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Optional: pretty URLs
[build]
  publish = "."

[[redirects]]
  from = "/linkconvert"
  to = "/linkconvertbeta/"
  status = 301
  
  # Ensure Netlify Forms stays on
[build.processing]
  skip_processing = false
[build.processing.forms]
  enabled = true

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML should not be cached by browsers
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Optionally also for the root path
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

    [[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

# netlify.toml  (Aquilario marketing site)
[[redirects]]
  from = "/linkconvert"
  to = "https://linkconvert.aquilario.com"
  status = 308
  force = true

[[redirects]]
  from = "/linkconvert/*"
  to = "https://linkconvert.aquilario.com/:splat"
  status = 308
  force = true


